### ISSUE TITLE
Issue report section error and firebase api key

### ISSUE THREAD

**Issue by SeeVetri** [PrinceSumberia/assets-management#2]
Hi .. when i install app in device .. everything seems to be ok .. but the issue report section make the app close when i click to open it .. also may i know where to get firebase api key .. it also show that error too ..

**Comment by PrinceSumberia** [comment]
The issue maybe with the missing API key. You can find the firebase API key inside your `google-services.json` file after you have successfully connected with the firebase account.

```
 "api_key": [
        {
          "current_key": "XXXXXXXXXXXXXXXX"
        }
]
```

`current_key` will be your firebase API key and inside `res >> values >> string.xml` replace  _place current_key value here_ in the following string value with your API key.
 
```
<string name="firebase_api">place current_key value here</string>
```

Hope this helps

**Comment by seesimon** [comment]
Hello sir..i have add already the firebase api .. but it's still remain same

**Comment by SeeVetri** [comment]
![IMG-20210501-WA0003](https://user-images.githubusercontent.com/61798398/116740452-a2666c80-aa27-11eb-8a65-61888b245f2a.jpg)

HELLO SIR THIS IS THE ERROR I GET .. AFTER STILL I PUT MY API ALREADY .. ITS ONLY EFFECT THE ISSUE SECTION

**Comment by PrinceSumberia** [comment]
I think the inventory is empty that's why you are getting null. Have you tried adding some assets/inventory first before issuing them? First, add some random inventory as well as users' data and check if it works.

**Comment by keerthik123** [comment]
hello sir i'm using the same app. For me also the same error

**Comment by keerthik123** [comment]
please help me sir

**Comment by keerthik123** [comment]
can you run the app and see ?

**Comment by PrinceSumberia** [comment]
Okay, I will look into the code and figure out what's wrong with the code. But first, can you confirm the following: 

- Have you created users both approver and normal users from the admin user dashboard. 
- Have you added some assets/products.
- If you have created users for each role, are their accounts verified.
- Now try to issue the assets.

If you have completed all the above-mentioned steps and you still get the error, then please let me know I will look into the issue. If not then please complete the above steps and check if the error still exists.

**Comment by SeeVetri** [comment]
Hello sir when create a user also getting error by making the app to shut down too sometime .. but it do create user sometimes i also don't know how .. but issue effect still same .. qr code scanner also making shut down error .. summore cant log out in normal or approval user section

**Comment by PrinceSumberia** [comment]
Ok, will check and let you know

**Comment by keerthik123** [comment]
i sir how to use the scan asset.

**Comment by keerthik123** [comment]
i sir how to use the scan asset.

**Comment by PrinceSumberia** [comment]
You have to scan the QR code generated after you have added the asset.

**Comment by keerthik123** [comment]
hi can i know why my realtime database not working
![firebase](https://user-images.githubusercontent.com/83503088/119936531-e794a480-bfbb-11eb-9d16-4758b4bf9fed.png)

**Comment by PrinceSumberia** [comment]
Hi @keerthik123, the app uses Firestore Database, not Realtime database. So you need to look into the Firestore Database option just above the Realtime Database option. I hope this helps. Cheers!

**Comment by PrinceSumberia** [comment]
Today I have gone through the project and found out the reason for the errors. And it seems like the Firebase API has changed since the app was last updated. 

The core API remains the same but the setup procedure appears to have changed along with other methods. So, I request you to try making the changes yourself, until the project is updated.
